apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: highlander
resources:
  - ../../base/highlander
  - cloudflare.yaml

images:
  - name: highlander
    newName: ghcr.io/nleahy/hello-vapor
    digest: sha256:5da94aec3d1575b52631235d4627fa379761242007fb4f84b556adc77f75b3e5