apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: highlander
resources:
  - ../../base/highlander
  - cloudflare.yaml

images:
  - name: highlander
    newName: ghcr.io/nleahy/hello-vapor
    digest: sha256:9f4c563c7aebe37883864de7002ed0608f0b6338aa4b4feb68244eec4f08aea8