apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: highlander
  name: highlander
  namespace: highlander
spec:
  replicas: 1
  selector:
    matchLabels:
      app: highlander
  template:
    metadata:
      labels:
        app: highlander
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
        - image: ghcr.io/nleahy/hello-vapor@sha256:b944a3ffcbd9c1abddd7205a662cdee8a2f412c9832ef56b98ddf65d9ee83b3b
          name: highlander
          args: 
          - "serve"
          - "--hostname"
          - "0.0.0.0"
          - "--port"
          - "9001"
          - "--env"
          - "development"
          env:
          - name: DATABASE_URL
            value: "postgres://app@highlander-db-rw.highlander:5432/app?sslmode=disable"
          - name: DATABASE_HOST
            value: "highlander-db-rw"
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: highlander-db-app
                key: password
          ports:
          -  containerPort: 9001
      imagePullSecrets:
      - name: ghcr-pull-secret