apiVersion: v1
data:
    mealie-tunnel-credential.json: ENC[AES256_GCM,data:9l90Nkyhnr9CVAUNk6kE6oWD6Ajb7BHZdZug2COLqp4PoverWg5LFFCIrM883Cl8cF6nSV3qjUd02JG13+m7hCnhNBWYuTSRMU16kNmytL2g1/Oj3KVtUFZBms8DrBV+VYLvioGi496eXNI77e4ekIO/DJIbjtaatt64aTT4EeSztWRFVNcBKrUpE3lv6M3F4DqnaTgFoWPShWXhCbXWM2S1lw6YbvU8llseLXvJ9Ztyhdpccj94tFpkchaCsl/c3Yvi/xwbogfuqRvnDWP2GBzzHHo2JTxP9dGyJ5vP9uP3FKRlFXym89qn42g=,iv:5Dg/cnC/obv+Nd1ZLzY+v/l7MIVM6/q/cAZTPjVIbeE=,tag:XmprlnxJ2cYmlizTqQRFeQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: "2025-10-16T18:12:19Z"
    name: mealie-tunnel-credentials
    namespace: mealie
    resourceVersion: "2691292"
    uid: d78ed8a9-c885-4ce8-90e4-6f4ac6cfcafa
type: Opaque
sops:
    age:
        - recipient: age1zhwwl4kztlsqdcc4x7tvxschrr2z0625uade2vzuf0rnaeemmusq5x7aen
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNnBVS215eHg5UWdVQ1RY
            VnpGdzJVa3c2K3ViOVVpY0FoOG4rTHA5eEU0Cm52bGg3enF2YU9zUFN4QytsR2Vk
            dmFRVksrcklPWWlma2Z3a3hnMXVyMncKLS0tIFdRbjdxdi96VUpjS1BDWVA3VGlP
            Rk5ZakNDVjMxL0JkVWJtbVRxcGpESGcKRbRlNfg1y8dKNK4XSOmmCWUn275F1qrD
            f+BUetJe9j6y78LjUibZgDPBqFQZQgaYjktcVvhL9i+SgCR7hsfHsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-16T18:12:47Z"
    mac: ENC[AES256_GCM,data:RsqA0fepJGY+TMUiZlBph4uj3d25tHPh5Y2LUVlxXp7DpAhDvuRLJhC/CwtYmMTsuFZs1rvYAbYoN0AdEU5+BhP571SbIsSJeoux6RMTpH47YGpyiP3A11tpYYtf9iC8t3M+bTAgXqGbPbuVqCXWldosmHDi2IBrjutyPeKtQDo=,iv:HDbmnRkoGQ+LBCO3wKYd5U1JwgNrN9+EerDIWLQP1Y8=,tag:RwCV59bcK08otku54e+D2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
