apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: foo
  namespace: database
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  enableSuperuserAccess: true
  storage:
    size: 1Gi
