apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: databases
spec:
  interval: 60m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.26.*"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: database
      interval: 60m

