apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: databases
spec:
  interval: 60m
  chart:
    spec:
      chart: cnpg/cloudnative-pg
      version: "0.26.*"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: databases
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
